name: Build and Deploy Code
# If you want it to work on only push:
# on: push

# If you want it to work on only pulls"
# on: pull_request

# If you want it to work on both:
on: [push, pull_request]

# If you want to specify which brancheS:
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "test_branch"

jobs:
  jobs1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 69haventyoupeopleeverheardofclosingthegoddamndoor?69
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: fastapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v2
      - name: Set up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: |
          pip install pytest
          pytest
